## **RADI608: Data Mining and Machine Learning**

### Assignment: KMeans
**Romen Samuel Rodis Wabina** <br>
Student, PhD Data Science in Healthcare and Clinical Informatics <br>
Clinical Epidemiology and Biostatistics, Faculty of Medicine (Ramathibodi Hospital) <br>
Mahidol University

Note: In case of Python Markdown errors, you may access the assignment through this GitHub [Link](https://github.com/rrwabina/RADI608/tree/main/Submitted)

### Question 1: <code>Find (by manual and show calculation steps) the appropriate centroids by using a KMeans clustering with Euclidean distance (K = 2)</code>

##### With a <code>k = 2</code>, we initialized a given centroid of group 1 at <code>$C_1$ = (1, 1)</code> and <code>$C_2$ = (1, 3)</code>. The $\mathbf{D_0}$ is a <code>(2, 6)</code> matrix that summarizes the distances of all centroids against the features and samples. 

\begin{equation*}
\begin{aligned}    
    \mathbf{D_0} = 
    \begin{bmatrix}
        {d_{11}} & {d_{12}} & {d_{13}} & {d_{14}} & {d_{15}} & {d_{16}}   \\
        {d_{21}} & {d_{22}} & {d_{23}} & {d_{24}} & {d_{25}} & {d_{26}}   \\
    \end{bmatrix}
\end{aligned}
\end{equation*}


##### We utilized the Euclidean distance to calculate the distance between the cluster centroid to each object. The scalar $d_{ij}$ determines the relative distance of the data to the current centroid at sample $i$ of feature $j$. The calculation below shows the Euclidean distance at iteration 0.

\begin{equation*}
\begin{aligned}
    d_{11} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{21} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{11} &= \sqrt{(1 - 1)^2 + (1 - 1)^2}          & d_{21} &= \sqrt{(1 - 1)^2 + (1 - 3)^2}\\
    d_{11} &= 0                                     & d_{21} &= 2    
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{12} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{22} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{12} &= \sqrt{(2 - 1)^2 + (1 - 1)^2}          & d_{22} &= \sqrt{(2 - 1)^2 + (1 - 3)^2}\\
    d_{12} &= 1                                     & d_{22} &= \sqrt{5}    
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{13} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{23} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{13} &= \sqrt{(1 - 1)^2 + (3 - 1)^2}          & d_{23} &= \sqrt{(1 - 1)^2 + (3 - 3)^2}\\
    d_{13} &= 2                                     & d_{23} &= 0
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{14} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{24} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{14} &= \sqrt{(5 - 1)^2 + (2 - 1)^2}          & d_{24} &= \sqrt{(5 - 1)^2 + (2 - 3)^2}\\
    d_{14} &= \sqrt{17}                             & d_{24} &= \sqrt{17}   
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{15} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{25} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{15} &= \sqrt{(4 - 1)^2 + (3 - 1)^2}          & d_{25} &= \sqrt{(4 - 1)^2 + (3 - 3)^2}\\
    d_{15} &= \sqrt{13}                             & d_{25} &= 3   
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{15} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{25} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{15} &= \sqrt{(5 - 1)^2 + (4 - 1)^2}          & d_{25} &= \sqrt{(5 - 1)^2 + (4 - 3)^2}\\
    d_{15} &= 5                                     & d_{25} &= \sqrt{17}   
\end{aligned}
\end{equation*}

##### Summarizing the calculations above, we now have the matrix $\mathbf{D_0}$ at iteration 0. We then now assign each object based on the minimum distance. For every feature $j$, we assign the sample with $1$ having the minimum distance. Otherwise, its value is 0. This may also be interchanged to other problems across literature but the result is still the same since we are dealing with binary values.   

\begin{equation*}
\begin{aligned}    
    \mathbf{D_0} = 
    \begin{bmatrix}
        0 & 1        & 2 & \sqrt{17} & \sqrt{13} & 5   \\
        2 & \sqrt{5} & 0 & \sqrt{17} & 3         & \sqrt{17}   \\
    \end{bmatrix}
    \longrightarrow
    \mathbf{G_0} = 
    \begin{bmatrix}
        1 & 1 & 0 & 1 & 0 & 0   \\
        0 & 0 & 1 & 0 & 1 & 1   \\
    \end{bmatrix}    
\end{aligned}
\end{equation*}

##### We then determine the centroids for iteration $1$. We calculate the new centroid of each group where both groups 1 and 2 have three members.

\begin{equation*}
\begin{aligned}
    C_{1} &= (\frac{1+2+5}{3}, \frac{1+1+2}{3})  & C_{2} &= (\frac{1+4+5}{3}, \frac{3+3+4}{3}) \\
    C_{1} &= (2.67, 1.33)                        & C_{2} &= (3.33, 3.33)
\end{aligned}
\end{equation*}

##### As shown above, the new centroids are <code>$C_1$ = (2.67, 1.33)</code> and <code>$C_2$ = (3.33, 3.33)</code>.

\begin{equation*}
\begin{aligned}
    d_{11} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{21} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{11} &= \sqrt{(1 - 2.67)^2 + (1 - 1.33)^2}    & d_{21} &= \sqrt{(1 - 3.33)^2 + (1 - 3.33)^2}\\
    d_{11} &= 1.7022925717983968                    & d_{21} &= 3.2951176003293114    
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{12} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{22} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{12} &= \sqrt{(2 - 2.67)^2 + (1 - 1.33)^2}    & d_{22} &= \sqrt{(2 - 3.33)^2 + (1 - 3.33)^2}\\
    d_{12} &= 0.7468600939935136                    & d_{22} &= 2.6828715958837837   
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{13} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{23} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{13} &= \sqrt{(1 - 2.67)^2 + (3 - 1.33)^2}    & d_{23} &= \sqrt{(1 - 3.33)^2 + (3 - 3.33)^2}\\
    d_{13} &= 2.3617366491630687                    & d_{23} &= 2.3532530675641326
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{14} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{24} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{14} &= \sqrt{(5 - 2.67)^2 + (2 - 1.33)^2}    & d_{24} &= \sqrt{(5 - 3.33)^2 + (2 - 3.33)^2}\\
    d_{14} &= 2.4244174558025273                    & d_{24} &= 2.1349004660639332
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{15} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{25} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{15} &= \sqrt{(4 - 2.67)^2 + (3 - 1.33)^2}    & d_{25} &= \sqrt{(4 - 3.33)^2 + (3 - 3.33)^2}\\
    d_{15} &= 2.1349004660639332                    & d_{25} &= 0.7468600939935136
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{16} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{26} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{16} &= \sqrt{(5 - 2.67)^2 + (4 - 1.33)^2}    & d_{26} &= \sqrt{(5 - 3.33)^2 + (4 - 3.33)^2}\\
    d_{16} &= 3.5436986327846784                    & d_{26} &= 1.799388785115657
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}    
    \mathbf{D_1} = 
    \begin{bmatrix}
        1.702 & 0.747 & 2.362 & 2.424 & 2.135 & 3.544   \\
        3.295 & 2.683 & 2.353 & 2.135 & 0.747 & 1.799   \\
    \end{bmatrix}
    \longrightarrow
    \mathbf{G_1} = 
    \begin{bmatrix}
        1 & 1 & 0 & 0 & 0 & 0   \\
        0 & 0 & 1 & 1 & 1 & 1   \\
    \end{bmatrix}    
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    C_{1} &= (\frac{1+2}{2}, \frac{1+1}{2})  & C_{2} &= (\frac{1+5+4+5}{4}, \frac{3+2+3+4}{4}) \\
    C_{1} &= (1.50, 1.00)                        & C_{2} &= (3.75, 3.00)
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{11} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{21} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{11} &= \sqrt{(1 - 1.50)^2 + (1 - 1.00)^2}    & d_{21} &= \sqrt{(1 - 3.75)^2 + (1 - 3.00)^2}\\
    d_{11} &= 0.500                                  & d_{21} &= 3.400    
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{12} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{22} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{12} &= \sqrt{(2 - 1.50)^2 + (1 - 1.00)^2}    & d_{22} &= \sqrt{(2 - 3.75)^2 + (1 - 3.00)^2}\\
    d_{12} &= 0.500                                 & d_{22} &= 2.658   
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{13} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{23} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{13} &= \sqrt{(1 - 1.50)^2 + (3 - 1.00)^2}    & d_{23} &= \sqrt{(1 - 3.75)^2 + (3 - 3.00)^2}\\
    d_{13} &= 2.062                                 & d_{23} &= 2.750
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{14} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{24} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{14} &= \sqrt{(5 - 1.50)^2 + (2 - 1.00)^2}    & d_{24} &= \sqrt{(5 - 3.75)^2 + (2 - 3.00)^2}\\
    d_{14} &= 3.640                                 & d_{24} &= 1.601
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{15} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{25} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{15} &= \sqrt{(4 - 1.50)^2 + (3 - 1.00)^2}    & d_{25} &= \sqrt{(4 - 3.75)^2 + (3 - 3.00)^2}\\
    d_{15} &= 3.202                                 & d_{25} &= 0.250 
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    d_{16} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2}  & d_{26} &= \sqrt{(q_1 - p_1)^2 + (q_2 - p_2)^2} \\
    d_{16} &= \sqrt{(5 - 1.50)^2 + (4 - 1.00)^2}    & d_{26} &= \sqrt{(5 - 3.75)^2 + (4 - 3.00)^2}\\
    d_{16} &= 4.610                                 & d_{26} &= 1.601   
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}    
    \mathbf{D_2} = 
    \begin{bmatrix}
        0.500 & 0.500 & 2.062 & 3.640 & 3.202 & 4.610   \\
        3.400 & 2.658 & 0.750 & 1.601 & 0.250 & 1.601   \\
    \end{bmatrix}
    \longrightarrow
    \mathbf{G_2} = 
    \begin{bmatrix}
        1 & 1 & 0 & 0 & 0 & 0   \\
        0 & 0 & 1 & 1 & 1 & 1   \\
    \end{bmatrix}    
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
    C_{1} &= (\frac{1+2}{2}, \frac{1+1}{2})  & C_{2} &= (\frac{1+5+4+5}{4}, \frac{3+2+3+4}{4}) \\
    C_{1} &= (1.50, 1.00)                        & C_{2} &= (3.75, 3.00)
\end{aligned}
\end{equation*}

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from time import time
from sklearn.metrics import pairwise_distances_argmin

def distance_formula(data, centroids):
    distance = []
    for value in data:
        for center in centroids:
            dis = np.sqrt((value[0] - center[0])**2 + (value[1] - center[1])**2)
            distance.append(dis)
    return distance

In [81]:
X = [[1, 1], [2, 1], [1, 3], [5, 2], [4, 3], [5, 4]]
centroid2 = [[2.67, 1.33], [3.33, 3.33]]
distance_formula(X, centroid2)

[1.7022925717983968,
 3.2951176003293114,
 0.7468600939935136,
 2.6828715958837837,
 2.3617366491630687,
 2.3532530675641326,
 2.4244174558025273,
 2.1349004660639332,
 2.1349004660639332,
 0.7468600939935136,
 3.5436986327846784,
 1.799388785115657]

In [75]:


X = [[1, 1], [2, 1], [1, 3], [5, 2], [4, 3], [5, 4]]
centroids = [[1, 1], [1, 3]]
centroid2 = [[2.67, 1.33], [3.33, 3.33]]
centroid3 = [[1.50, 1.00], [3.75, 3.00]]
def distance_formula(data, centroids):
    distance = []
    for value in data:
        for center in centroids:
            dis = np.sqrt((value[0] - center[0])**2 + (value[1] - center[1])**2)
            distance.append(dis)
    return distance

def kmeans(X, initial_centers, n_clusters = 2):
    m, n = X.shape
    centers = initial_centers
    iteration = 0
    while True:
        print(f'=================Centers:=================')
        print(centers)
        labels = pairwise_distances_argmin(X, centers)
        new_centers = []
        for i in range(n_clusters):
            new_centers.append(X[labels == i].mean(axis=0))
        new_centers = np.array(new_centers)
        print(f'New Center: \n {np.round(new_centers, 2)}')

        pred = pairwise_distances_argmin(X, new_centers)
        print(pred)
        # plt.figure(figsize=(5, 2))
        # plt.title(f"Iteration: {iteration}")
        # plt.scatter(X[:, 0], X[:, 1], c=pred)
        # plt.scatter(new_centers[:, 0], new_centers[:, 1], s=100, c = "black", alpha = 0.6)

        if(np.allclose(centers, new_centers)):
            break
        else:
            centers = new_centers
            iteration += 1
    print(f"Done in {iteration} iterations")
    return centers
        
def predict(X, centers):
    return pairwise_distances_argmin(X, centers)

X = np.array([[1, 1], [2, 1], [1, 3], [5, 2], [4, 3], [5, 4]])
initial_centers = [[1, 1], [1, 3]]
start = time()
preds = predict(X, kmeans(X, initial_centers))

=================Centers:=================
[[1, 1], [1, 3]]
New Center: 
 [[2.67 1.33]
 [3.33 3.33]]
[0 0 0 1 1 1]
=================Centers:=================
[[2.66666667 1.33333333]
 [3.33333333 3.33333333]]
New Center: 
 [[1.33 1.67]
 [4.67 3.  ]]
[0 0 0 1 1 1]
=================Centers:=================
[[1.33333333 1.66666667]
 [4.66666667 3.        ]]
New Center: 
 [[1.33 1.67]
 [4.67 3.  ]]
[0 0 0 1 1 1]
Done in 2 iterations
